server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus,info"
  endpoint:
    health:
      show-details: always       # show component details
      show-components: always    # include the components tree
  metrics:
    tags:
      application: edge-service

logging:
  level:
    com.serotonin.bacnet4j: DEBUG
    org.metrolink.bas.connector.bacnet: DEBUG

connectors:
  active: bacnet
  sim:
    ai1Start: 22.5
    ai1Drift: 0.15
    periodMs: 750
  bacnet:
    deviceInstance: 12345
    apduTimeoutMs: 3000
    apduSegTimeoutMs: 2000
    apduRetries: 1
    udpPort: 47808
    bindAddress: 192.168.1.6      # <- your PC's LAN IP
    broadcast: 192.168.1.255    # <- your subnet broadcast (.255 for /24)