server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus,info"
  endpoint:
    health:
      show-details: always       # show component details
      show-components: always    # include the components tree
  metrics:
    tags:
      application: edge-service

connectors:
  active: sim  # default behavior
  sim:
    ai1Start: 22.5
    ai1Drift: 0.15
    periodMs: 750
  bacnet:
    deviceInstance: 12345
    apduTimeoutMs: 3000
    covRenewSec: 120
    defaultCovIncrement: 0.1
    bbmdEnabled: false